version: "3.4"

services:
  sampleproject:
    image: websocket-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
