version: "3.4"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - 3000:3000
